version: "3.8"

services:
  backend:
    build:
      context: ./backend
    image: harikrishnanas/movies-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    image: harikrishnanas/movies-frontend
    ports:
      - "80:80"
